version: '3.8'

services:
  server:
    image: vaishchavandocker/freshcart-server:latest
    container_name: freshkart-server
    networks:
      - freshkart-network
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - ./server/.env

  client:
    image: vaishchavandocker/freshcart-client:latest
    container_name: freshkart-client
    networks:
      - freshkart-network
    ports:
      - "8080:80"  
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8
    container_name: freshkart-mongodb
    networks:
      - freshkart-network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  freshkart-network:
    driver: bridge
